import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { cn } from "@/lib/utils";
import Footer from "@/components/footer";

const dm_Sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(dm_Sans.className, " min-h-[100dvh]")}>
        <ClerkProvider>
          <Header />
          <main className="flex min-h-screen flex-col items-center justify-between  max-w-[1300px] px-3 mx-auto ">
            {children}
          </main>
          <Footer/>
        </ClerkProvider>
      </body>
    </html>
  );
}
